apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresclusters.k8s.crossplane.grazdev.io
spec:
  group: k8s.crossplane.grazdev.io
  names:
    kind: XPostgresCluster
    plural: xpostgresclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              instances:
                type: integer
                description: "Number of PostgreSQL instances in the cluster."
                default: 1
              hibernation:
                type: string
                description: "Set to 'on' to hibernate the cluster, 'off' to wake it up."
                default: "off"
            required:
            - instances
