apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-green-xpostgrescluster-patcher
rules:
- apiGroups:
  - "k8s.crossplane.grazdev.io"
  resources:
  - "xpostgresclusters"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-green-patch-xpostgrescluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-green-xpostgrescluster-patcher
subjects:
- kind: ServiceAccount
  name: kube-green-controller-manager
  namespace: kube-green